#bitbucket-pipelines.yml
pipelines:
  branches:
    master:
    - step:
        name: Deploy to Web
        image: alpine
        deployment: production
        script:
          - ssh ubuntu@54.149.131.30
          - cd vrs-backend
          - git pull https://sobhanthakur@bitbucket.org/vrscheduler/vrs-backend.git master
          - php bin/console cache:clear --env=prod
          - sudo chmod -R 777 var/cache/ var/logs/ var/sessions/