<?php

namespace AppBundle\Repository;

/**
 * ChecklistItemImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistItemImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
