<?php

namespace AppBundle\Repository;

/**
 * IntegrationqbotokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegrationqbotokensRepository extends \Doctrine\ORM\EntityRepository
{
}
