<?php

namespace AppBundle\Repository;

/**
 * IssueandtaskimagestotasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueandtaskimagestotasksRepository extends \Doctrine\ORM\EntityRepository
{
}
