<?php

namespace AppBundle\Repository;

/**
 * IssueandtaskimagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueandtaskimagesRepository extends \Doctrine\ORM\EntityRepository
{
}
