<?php

namespace AppBundle\Repository;

/**
 * IssueimagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueimagesRepository extends \Doctrine\ORM\EntityRepository
{
}
