<?php

namespace AppBundle\Repository;

/**
 * IssueandtaskimagestotasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
/**
 * Class IssueandtaskimagestotasksRepository
 * @package AppBundle\Repository
 */
/**
 * Class IssueandtaskimagestotasksRepository
 * @package AppBundle\Repository
 */
class IssueandtaskimagestotasksRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $taskID
     * @return mixed
     */
    public function GetImagesByTaskID($taskID)
    {
        return $this->createQueryBuilder('i')
            ->select('t.imageName AS Image')
            ->leftJoin('i.issueAndtaskimageid','t')
            ->where('i.taskId='.$taskID)
            ->getQuery()
            ->execute();
    }
}
