<?php

namespace AppBundle\Repository;

/**
 * PropertyStatusesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyStatusesRepository extends \Doctrine\ORM\EntityRepository
{
}
