services:
    vrscheduler.base_service:
        abstract: true
        class: AppBundle\Service\BaseService
        calls:
            - [setServiceContainer, ['@service_container']]
            - [setLogger, ['@monolog.logger.exception']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setTranslator, ['@translator.default']]
    vrscheduler.request_listener:
        class: AppBundle\EventListener\RequestListener
        parent: vrscheduler.base_service
        arguments:
            - '@monolog.logger.api'
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
            - {name: monolog.logger, channel: api}
        public: true
    vrscheduler.response_listener:
        class: AppBundle\EventListener\ResponseListener
        parent: vrscheduler.base_service
        arguments: ["@monolog.logger.api"]
        tags:
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
    vrscheduler.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        parent: vrscheduler.base_service
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}
            - {name: monolog.logger, channel: exception}
        public: true

    vrscheduler.authentication_service:
        class: AppBundle\Service\AuthenticationService
        parent: vrscheduler.base_service
        public: true

    vrscheduler.api_response_service:
        class: AppBundle\Service\ApiResponse
        parent: vrscheduler.base_service
        public: true

    vrscheduler.integration_service:
        class: AppBundle\Service\IntegrationsService
        parent: vrscheduler.base_service
        public: true

    vrscheduler.file_export:
        class: AppBundle\Service\FileExportService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.filter_service:
        class: AppBundle\Service\FilterService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.map_properties:
        class: AppBundle\Service\MapPropertiesService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.map_staffs:
        class: AppBundle\Service\MapStaffsService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.map_task_rules:
        class: AppBundle\Service\MapTaskRulesService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.map_wage_item:
        class: AppBundle\Service\MapWageItemsService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.billing_approval:
        class: AppBundle\Service\BillingApprovalService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.timetracking_approval:
        class: AppBundle\Service\TimeTrackingApprovalService
        parent: vrscheduler.base_service
        public: true
    vrscheduler.sync_logs:
        class: AppBundle\Service\SyncLogsService
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_authentication_service:
        class: AppBundle\Service\AuthenticationPublicService
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_properties_service:
       class: AppBundle\Service\propertyDetailsServices
       parent: vrscheduler.base_service
       public: true

    vrscheduler.public_owners_service:
        class: AppBundle\Service\OwnerDetailsServices
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_general_service:
        class: AppBundle\Service\GeneralServices
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_region_groups_service:
        class: AppBundle\Service\RegionGroupsServices
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_regions_service:
        class: AppBundle\Service\RegionsServices
        parent: vrscheduler.base_service
        public: true

    vrscheduler.public_property_bookings_service:
        class: AppBundle\Service\PropertyBookingsService
        parent: vrscheduler.base_service
        public: true
